package com.example.state

object AppStrings {
    // App Branding & Global Header
    fun cine(lang: AppLanguage) = "Cine"
    fun stream(lang: AppLanguage) = "Stream"
    fun adminPanel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "Admin Panel" else "Admin Panel"
    fun adminPortal(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لوحة التحكم الإدارية" else "Admin Portal"
    fun adminLetter(lang: AppLanguage) = "A"
    fun onlineStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "متصل" else "Online"
    fun navigationMenu(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "القائمة الرئيسية" else "Navigation Menu"

    // Navigation Screens
    fun dashboard(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لوحة التحكم" else "Dashboard"
    fun users(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المستخدمين" else "Users"
    fun appUpdates(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات التطبيق" else "App Updates"
    fun extensionsUpdates(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات الإضافات" else "Extensions Hub"
    fun globalConfig(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإعدادات العامة" else "Global Config"
    fun notifications(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإشعارات" else "Notifications"
    fun settings(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإعدادات" else "Settings"
    fun diagnostics(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص وتشخيص" else "Diagnostics"
    fun auditLogs(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجلات الأمان" else "Audit Logs"
    fun reports(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بلاغات المستخدمين" else "User Reports"
    fun profile(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الملف الشخصي" else "Profile"
    fun logout(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تسجيل الخروج" else "Sign Out"

    // Subtitles
    fun usersSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إدارة المشتركين والصلاحيات" else "Subscribers & Permissions"
    fun appUpdatesSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشر تحديثات OTA لعملاء التطبيق" else "Publish OTA APK releases"
    fun globalConfigSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع الصيانة، حماية DRM، والسياسات" else "Maintenance, DRM & Policies"
    fun notificationsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال إشعارات جماعية ومخصصة" else "Push Broadcasts"
    fun extensionsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافات ومصادر الكشط" else "APK Scrapers & Modules"
    fun reportsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "متابعة مشاكل البث وبلاغات الأعطال" else "Review client issues & bugs"
    fun settingsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفضيلات ومظهر التطبيق" else "Appearance & Preferences"
    fun profileSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بيانات حساب المشرف" else "Admin account settings"
    fun auditLogsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجلات الأمان والأحداث" else "Security & Audit events"
    fun diagnosticsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص السجلات والأعطال الحية" else "Live crash & log viewer"
    fun userDetailSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعديل القيود والصلاحيات" else "Account constraints"

    // Common Actions
    fun saveChanges(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ التغييرات" else "Save Changes"
    fun save(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ" else "Save"
    fun cancel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إلغاء" else "Cancel"
    fun confirm(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد" else "Confirm"
    fun delete(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف" else "Delete"
    fun back(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رجوع" else "Back"
    fun refresh(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديث" else "Refresh"
    fun search(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بحث..." else "Search..."
    fun reset(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعادة ضبط" else "Reset"
    fun copy(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نسخ" else "Copy"
    fun copied(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم النسخ بنجاح" else "Copied successfully"
    fun close(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إغلاق" else "Close"
    fun edit(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعديل" else "Edit"
    fun add(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة" else "Add"
    fun system(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "النظام" else "SYSTEM"
    fun welcomeAdmin(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مرحباً بك، المشرف" else "Welcome back, Admin"
    fun adminAccount(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حساب المشرف" else "Admin Account"

    // Users Screen (Dashboard)
    fun addUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة مستخدم" else "Add User"
    fun totalUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إجمالي المستخدمين" else "Total Users"
    fun activeNow(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط الآن" else "Active Now"
    fun proUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مستخدمين PRO" else "PRO Users"
    fun inactive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط" else "Inactive"
    fun searchUsersPlaceholder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "... البحث بالاسم، البريد الإلكتروني أو الـ UID" else "Search by name, email or UID..."
    fun filterAll(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الكل" else "All"
    fun filterActive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط" else "Active"
    fun filterInactive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط" else "Inactive"
    fun filterPro(lang: AppLanguage) = "PRO"
    fun filterBanned(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "محظور" else "Restricted"
    fun sortNewestFirst(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الأحدث أولاً" else "Newest First"
    fun sortRecent(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "النشاط الأخير" else "Recent"
    fun sortName(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الاسم (أ - ي)" else "Name (A-Z)"
    fun userListTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قائمة المستخدمين" else "User List"
    fun userCountBadge(count: Int, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "$count مستخدمين" else "$count Users"
    fun neverLoggedIn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لم يسبق له الدخول" else "Never logged in"
    fun activeStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط" else "Active"
    fun inactiveStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط" else "Inactive"
    fun adminBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أدمن" else "ADMIN"
    fun proBadge(lang: AppLanguage) = "PRO"
    fun restrictedBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مقيد" else "RESTRICTED"
    fun viewDetails(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "عرض التفاصيل والصلاحيات" else "View Details & Permissions"
    fun upgradeToPro(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "ترقية إلى حساب PRO" else "Upgrade to PRO"
    fun revokePro(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إلغاء اشتراك PRO" else "Revoke PRO"
    fun restrictUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر / تقييد المستخدم" else "Restrict / Ban User"
    fun unbanUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فك الحظر عن المستخدم" else "Unban User"
    fun deleteUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف المستخدم" else "Delete User"
    fun confirmDeleteUserTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد حذف المستخدم" else "Confirm User Deletion"
    fun confirmDeleteUserMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "هل أنت متأكد من رغبتك في حذف هذا المستخدم نهائياً؟ لا يمكن التراجع عن هذا الإجراء." else "Are you sure you want to permanently delete this user? This action cannot be undone."
    fun addNewUserDialogTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة مستخدم جديد" else "Add New User"
    fun username(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اسم المستخدم" else "Username"
    fun email(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "البريد الإلكتروني" else "Email Address"
    fun optionalPassword(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "كلمة المرور (اختياري)" else "Password (Optional)"
    fun proAccountCheckbox(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل اشتراك PRO فورياً" else "Enable PRO Plan Immediately"
    fun adminRoleCheckbox(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منح صلاحيات المشرف (Admin)" else "Grant Administrator Privileges"
    fun noUsersMatch(query: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد نتائج مطابقة لـ '$query'" else "No users match '$query'"
    fun noUsersYet(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا يوجد مستخدمين مسجلين حتى الآن" else "No registered users yet"
    fun usersAutoSyncDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سيتم مزامنة حسابات عملاء CineStream تلقائياً هنا في الوقت الفعلي" else "CineStream client users will automatically synchronize here in real time"
    fun resetSearchAndFilters(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعادة ضبط البحث والتصفية" else "Reset Search & Filters"
    fun syncingUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري مزامنة مستخدمي CineStream..." else "Syncing CineStream users..."

    // App Updates (OTA) Screen
    fun appUpdatesTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات التطبيق (OTA)" else "App Updates (OTA)"
    fun currentRelease(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإصدار الحالي في الإنتاج" else "Current Production Release"
    fun configureNewRelease(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تهيئة ونشر تحديث جديد" else "Configure & Publish New Release"
    fun versionNameField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اسم الإصدار (مثل 2.5.0)" else "Version Name (e.g. 2.5.0)"
    fun versionCodeField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رقم البناء الداخلي (Build Code)" else "Build Code (e.g. 25)"
    fun apkDownloadUrlField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رابط تحميل ملف APK المباشر" else "Direct APK Download URL"
    fun apkSha256Field(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بصمة التحقق والتشفير (SHA-256)" else "SHA-256 Checksum (Optional)"
    fun mandatoryUpdate(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فرض التحديث الإجباري" else "Mandatory Update"
    fun mandatoryUpdateDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منع فتح التطبيق حتى يتم تحديثه" else "Block older versions until updated"
    fun minVersionCodeField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحد الأدنى لرقم الإصدار المدعوم" else "Minimum Supported Build Code"
    fun releaseNotesField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجل التغييرات والميزات الجديدة" else "Release Notes & Changelog"
    fun publishReleaseNow(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشر التحديث لجميع المستخدمين" else "Publish Release Now"
    fun updatePreviewTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معاينة رسالة التحديث للمستخدم" else "User-Facing Update Dialog Preview"
    fun confirmPublishDialogTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد نشر تحديث التطبيق؟" else "Confirm OTA Release Publish?"
    fun confirmPublishDialogMsg(versionName: String, versionCode: String, lang: AppLanguage) = 
        if (lang == AppLanguage.ARABIC) "سيتم إشعار جميع أجهزة المستخدمين فورياً بالإصدار الجديد $versionName (Build $versionCode)." 
        else "All user devices will be immediately notified of version $versionName (Build $versionCode)."
    fun uploadApkFromDevice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رفع ملف APK من جهازك" else "Upload APK from Device"
    fun uploadApkDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اختيار ملف التحديث لحساب بصمة SHA-256 ورفعه إلى السيرفر تلقائياً" else "Pick APK to auto-calculate SHA-256 and upload to server"
    fun analyzingApk(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري فحص الملف وحساب بصمة SHA-256..." else "Analyzing APK & computing SHA-256..."
    fun uploadingApk(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري رفع ملف APK إلى السيرفر..." else "Uploading APK to server..."
    fun uploadApkSuccess(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم رفع ملف APK وحساب البصمة بنجاح!" else "APK uploaded & SHA-256 computed successfully!"
    fun hashCalculatedNotice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم حساب بصمة التشفير SHA-256 بنجاح. يمكنك إدخال رابط التحميل يدوياً." else "SHA-256 computed successfully. You may enter download link manually."
    fun broadcastNotificationToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال إشعار فوري لجميع المستخدمين بالتحديث" else "Broadcast push alert to all users"
    fun broadcastNotificationDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال تنبيه جماعي فوري ينبه الأجهزة بوجود الإصدار الجديد" else "Send instant push broadcast to all active devices"
    fun restoreCurrentValues(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "استعادة بيانات الإصدار الحالي" else "Restore Current Values"

    // Global Config Screen
    fun globalConfigTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإعدادات والسياسات العامة" else "Global Config & Policies"
    fun maintenanceSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع الصيانة العام" else "Global Maintenance Mode"
    fun maintenanceToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل وضع الصيانة" else "Enable Maintenance Mode"
    fun maintenanceToggleDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إيقاف خوادم البث مؤقتاً وعرض شاشة الصيانة" else "Temporarily pause streaming and show maintenance screen"
    fun maintenanceTitleField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "عنوان شاشة الصيانة" else "Maintenance Screen Title"
    fun maintenanceMessageField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رسالة الصيانة للمستخدمين" else "Maintenance Message"
    fun minClientVersionField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحد الأدنى لإصدار التطبيق المطلوب" else "Minimum Required Client Version"
    fun securityDrmSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حماية المحتوى والأمان (DRM)" else "Content Protection & Security (DRM)"
    fun antiTamperToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص سلامة الحزمة (Anti-Tamper)" else "Anti-Tamper & Signature Verification"
    fun antiTamperDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منع تشغيل نسخ التطبيق المعدلة أو غير الرسمية" else "Block modified or tampered client APKs"
    fun screenshotBlockToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر لقطات وتسجيل الشاشة (DRM Flag Secure)" else "Block Screenshots & Recording (FLAG_SECURE)"
    fun screenshotBlockDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر تسجيل الشاشة لحماية البث من القرصنة" else "Prevent screen recording to protect streams"
    fun rootDetectionToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر الأجهزة المروتة (Root Detection)" else "Root & Emulator Detection"
    fun rootDetectionDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تقييد الأجهزة التي تمتلك صلاحيات Root" else "Restrict access on rooted and emulated devices"
    fun offlinePolicySection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سياسات التحميل بدون إنترنت" else "Offline Download Policies"
    fun downloadExpiryField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية الفيديوهات المحملة (بالأيام)" else "Downloaded Media Expiry (Days)"
    fun maxOfflineDownloadsField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحد الأقصى للملفات المحملة لكل جهاز" else "Max Offline Downloads per Device"
    fun adPolicySection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سياسات الإعلانات للمستخدم المجاني" else "Ad Policies for Free Tier"
    fun adIntervalField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الفترة الزمنية بين الإعلانات الإجبارية (بالدقائق)" else "Interval Between Forced Ads (Minutes)"
    fun saveGlobalPolicies(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ السياسات العامة" else "Save Global Policies"
    fun policiesSavedSuccess(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم حفظ الإعدادات بنجاح" else "Policies saved successfully"

    // Extensions Screen
    fun extensionsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديثات ومصادر الكشط" else "Scraper Modules & Extensions"
    fun registeredScrapers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الكاشطات المسجلة في التطبيق" else "Registered Scraper Modules"
    fun addExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة كاشط جديد" else "Add Scraper Module"
    fun editExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعديل الكاشط" else "Edit Scraper Module"
    fun deleteExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف الكاشط" else "Delete Scraper Module"
    fun confirmDeleteExtTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد حذف الكاشط" else "Confirm Scraper Deletion"
    fun confirmDeleteExtMsg(name: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "هل أنت متأكد من حذف كاشط '$name' نهائياً؟" else "Are you sure you want to delete '$name' scraper?"
    fun extensionNameField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اسم الكاشط أو المصدر" else "Scraper Name"
    fun extensionPackageField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معرف الحزمة (Package ID)" else "Package ID"
    fun extensionVersionField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إصدار الكاشط (Version)" else "Extension Version"
    fun extensionApkUrlField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رابط ملف التحميل (DEX / APK)" else "Download File URL (DEX/APK)"
    fun extensionEnabledToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل الكاشط في التطبيق" else "Enable Scraper in Client"
    fun directJsonEditor(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المحرر السريع لكود الـ JSON" else "Direct Extensions JSON Editor"
    fun saveJsonConfig(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ كود الـ JSON" else "Save JSON Config"
    fun noExtensionsFound(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد إضافات مسجلة حالياً" else "No extensions registered yet"

    // Notifications Screen
    fun notificationsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال الإشعارات" else "Push Notifications"
    fun sendBroadcast(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إنشاء إشعار جديد" else "Create New Broadcast"
    fun notificationHistory(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجل الإشعارات المرسلة" else "Notification History"
    fun notifTitleField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "عنوان الإشعار" else "Notification Title"
    fun notifBodyField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نص الإشعار" else "Notification Message"
    fun targetAudience(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الفئة المستهدفة" else "Target Audience"
    fun targetAllUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جميع المستخدمين" else "All Users"
    fun targetProUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مشتركو PRO فقط" else "PRO Members Only"
    fun targetFreeUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المستخدمون المجانيون" else "Free Tier Users"
    fun deepLinkUrlField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رابط التوجيه المباشر (اختياري)" else "Deep Link URL (Optional)"
    fun sendNow(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال الإشعار الآن" else "Send Broadcast Now"
    fun sending(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري الإرسال..." else "Sending..."
    fun confirmSendNotifTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد إرسال الإشعار الجماعي" else "Confirm Push Broadcast"
    fun confirmSendNotifMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سيتم إرسال هذا التنبيه فورياً إلى الأجهزة المحددة." else "This push alert will be immediately delivered to selected devices."
    fun noNotifHistory(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد إشعارات سابقة في السجل" else "No sent notifications in history"

    // Settings Screen
    fun settingsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعدادات التطبيق" else "App Settings"
    fun appearance(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المظهر والتصميم" else "Appearance & Theme"
    fun darkTheme(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المظهر الداكن (Dark)" else "Dark Theme"
    fun darkThemeDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع مريح للعين وألوان داكنة أنيقة" else "Comfortable dark palette for nighttime"
    fun lightTheme(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المظهر الفاتح (Light)" else "Light Theme"
    fun lightThemeDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع مشرق وعالي التباين" else "Crisp high-contrast bright palette"
    fun language(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لغة التطبيق" else "App Language"
    fun languageDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "يدعم التطبيق اللغتين العربية والإنجليزية" else "Switch between Arabic (RTL) and English (LTR)"
    fun notificationPreferences(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفضيلات الإشعارات" else "Notification Preferences"
    fun enableNotifications(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل الإشعارات" else "Enable In-App Notifications"
    fun soundAlerts(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تنبيهات صوتية" else "Sound Alerts"
    fun vibration(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الاهتزاز عند الأحداث" else "Vibration Feedback"
    fun testNotification(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال إشعار تجريبي" else "Send Test Notification"
    fun testNotifSentMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم إرسال الإشعار التجريبي بنجاح!" else "Test notification sent successfully!"
    fun systemInfo(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معلومات النظام والاتصال" else "System Information"
    fun appVersion(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إصدار لوحة التحكم" else "Admin Portal Version"
    fun connectedProject(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مشروع Firebase المتصل" else "Connected Firebase Project"
    fun systemDiagnosticsBtn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فتح فحص وتشخيص النظام" else "Open System Diagnostics"

    // User Detail Screen
    fun userDetailTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفاصيل المستخدم والصلاحيات" else "User Details & Permissions"
    fun userInfoSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المعلومات الأساسية والحساب" else "Account & Profile Details"
    fun userPermissionsSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحيات استخدام التطبيق" else "App Feature Permissions"
    fun canWatch(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية المشاهدة والبث المباشر" else "Watching & Streaming Access"
    fun canWatchDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح للمستخدم بمشاهدة الأفلام والمسلسلات" else "Allow user to watch video streams"
    fun canDownload(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية التحميل بدون إنترنت" else "Offline Download Access"
    fun canDownloadDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بتحميل الحلقات والأفلام للهاتف" else "Allow offline video downloads"
    fun canChat(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية الدردشة وغرف النقاش" else "Chat & Community Rooms"
    fun canChatDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بالمشاركة في محادثات وغرف المشاهدة الجماعية" else "Allow participating in public chats"
    fun canStory(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية نشر القصص ومقاطع الفيديو" else "Stories & Clip Publishing"
    fun canStoryDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بنشر الستوري ومقاطع الفيديو القصيرة" else "Allow publishing user stories and clips"
    fun canP2P(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية المشاركة عبر شبكة P2P المحلية" else "Local P2P Share Access"
    fun canP2PDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بنقل الملفات محلياً بدون إنترنت" else "Allow offline peer-to-peer file sharing"
    fun canComment(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية التعليق وإبداء الآراء" else "Media Comments Access"
    fun canCommentDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بالتعليق على الأفلام والمسلسلات" else "Allow commenting on media content"
    fun canUpload(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية رفع المحتوى" else "Content Upload Access"
    fun canUploadDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح برفع الفيديوهات والملفات (خاص)" else "Allow publishing & uploading media content"
    fun canRequest(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحية طلب محتوى جديد" else "Media Request Access"
    fun canRequestDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "السماح بطلب إضافة أفلام ومسلسلات جديدة" else "Allow submitting movie & show requests"
    fun roleAndSubscription(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الرتبة ونوع الاشتراك" else "Role & Subscription Tier"
    fun isProSubscriber(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك بريميوم (PRO)" else "Premium PRO Subscriber"
    fun isAdministrator(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحيات المشرف (Administrator)" else "Administrator Privileges"
    fun grantAdminToggle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صلاحيات المدير الكاملة (Administrator)" else "Full Administrator Privileges"
    fun saveUserPermissions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ صلاحيات المستخدم" else "Save User Permissions"

    // Diagnostics & Logs
    fun diagnosticsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فحص وتشخيص النظام" else "System Diagnostics"
    fun auditLogsTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجلات الأمان والأحداث" else "Security & Audit Logs"
    fun profileTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الملف الشخصي للمشرف" else "Admin Profile"
    fun emailField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "البريد الإلكتروني" else "Email Address"
    fun uidField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معرف الحساب (UID)" else "Account UID"
    fun roleField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الرتبة" else "Role"
    fun createdAtField(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تاريخ الإنشاء" else "Created At"

    // Login Screen
    fun loginTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تسجيل الدخول للإدارة" else "Admin Sign In"
    fun loginSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أدخل بيانات حساب المشرف للمتابعة" else "Sign in to access CineStream portal"
    fun adminEmail(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "البريد الإلكتروني" else "Admin Email"
    fun password(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "كلمة المرور" else "Password"
    fun rememberMe(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تذكرني" else "Remember me"
    fun forgotPassword(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نسيت كلمة المرور؟" else "Forgot Password?"
    fun signInButton(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "دخول لوحة التحكم" else "Sign In"
    fun signInWithGoogle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الدخول بواسطة Google" else "Sign in with Google"
    fun orDivider(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أو" else "OR"
    fun restrictedAccess(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منطقة محظورة • للمشرفين المصرح لهم فقط" else "Restricted Access • Authorized Administrators Only"
    fun resetPasswordTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "استعادة كلمة المرور" else "Reset Password"
    fun resetPasswordDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أدخل بريدك الإلكتروني كمسؤول وسنرسل لك رابط إعادة تعيين كلمة المرور." else "Enter your administrator email address. A reset link will be sent to your inbox."
    fun sendResetLink(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال الرابط" else "Send Link"
    fun loading(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري التحميل..." else "Loading..."
    fun processing(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري المعالجة..." else "Processing..."
    fun saving(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "جاري الحفظ..." else "Saving..."

    // Phase C1: Account Security & Global Ban
    fun accountSecurityTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أمان وحالة الحساب العام" else "Account Security & Global Ban"
    fun accountGoodStanding(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحساب نشط وفي وضع نظامي" else "Account is in good standing"
    fun accountBanned(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحساب محظور عامةً" else "ACCOUNT BANNED"
    fun accountBannedDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم إيقاف هذا الحساب عن استخدام جميع خدمات CineStream" else "Suspended across all CineStream services"
    fun banExpiredBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "انتهت فترة الحظر" else "BAN EXPIRED"
    fun banExpiredDesc(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "انتهت مدة الحظر المؤقت، يمكن رفع القيد أو تجديد الحظر" else "Temporary ban has lapsed. Can be lifted or renewed"
    fun banAccountBtn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر الحساب العام" else "Ban Account"
    fun unbanAccountBtn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فك الحظر واستعادة الحساب" else "Lift Ban / Restore Account"
    fun banReasonLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سبب الحظر" else "Ban Reason"
    fun banDurationLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مدة الحظر" else "Ban Duration"
    fun permanentBan(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر دائم (بدون تاريخ انتهاء)" else "Permanent (No Expiry)"
    fun ban24h(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "24 ساعة" else "24 Hours"
    fun ban3Days(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "3 أيام" else "3 Days"
    fun ban7Days(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "7 أيام" else "7 Days"
    fun ban30Days(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "30 يوماً" else "30 Days"
    fun customDays(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مدة مخصصة" else "Custom Days"
    fun banReasonViolation(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مخالفة شروط الخدمة والسياسات" else "Terms of Service violation"
    fun banReasonAbuse(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "محتوى غير لائق أو إساءة في المحادثات" else "Harassment or inappropriate behavior"
    fun banReasonSuspicious(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشاط احتيالي أو مشاركة حسابات غير مصرح بها" else "Suspicious activity or account sharing"
    fun banReasonCopyright(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "انتهاك حقوق الملكية الفكرية" else "Copyright or piracy violation"
    fun banExpiresAtLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "ينتهي الحظر في:" else "Ban expires on:"
    fun banPermanentNotice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر دائم غير محدد بمدة" else "Permanent suspension"

    // Phase C1: Subscription Management
    fun subscriptionSectionTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إدارة الاشتراك والترقية (PRO/VIP)" else "Subscription & Pro Management"
    fun activeProBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك PRO نشط" else "Active PRO"
    fun activeVipBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك VIP نشط" else "Active VIP"
    fun expiredProBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك منتهي الصلاحية" else "EXPIRED PRO"
    fun freeTierBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "خطة مجانية" else "Free Plan"
    fun grantOrExtendSub(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "منح / تمديد الاشتراك" else "Grant / Extend Subscription"
    fun revokeSubBtn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إلغاء الاشتراك وإعادة للخطة المجانية" else "Revoke to Free Plan"
    fun selectTier(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اختر فئة الاشتراك" else "Select Subscription Tier"
    fun sub1Month(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "شهر واحد (30 يوماً)" else "1 Month (30 Days)"
    fun sub3Months(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "3 أشهر (90 يوماً)" else "3 Months (90 Days)"
    fun sub6Months(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "6 أشهر (180 يوماً)" else "6 Months (180 Days)"
    fun sub1Year(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سنة كاملة (365 يوماً)" else "1 Year (365 Days)"
    fun subLifetime(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مدى الحياة (دائم)" else "Lifetime (Indefinite)"
    fun subExpiresAt(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تاريخ انتهاء الاشتراك:" else "Subscription expires on:"
    fun subExpiredOn(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "انتهى الاشتراك بتاريخ:" else "Subscription expired on:"
    fun subLifetimeNotice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك مدى الحياة (بدون تاريخ انتهاء)" else "Lifetime subscription (no expiration date)"
    fun featureRestrictionsSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيود الميزات والخدمات الفردية" else "Individual Feature Restrictions"

    // Phase C2: Managed Extensions
    fun managedExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافات الكشط المُدارة" else "Managed Extensions"
    fun managedExtensionsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعدادات المصادر الديناميكية للمشغّل" else "Dynamic scraper catalog & configuration"
    fun managedExtensionsBanner(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافات الكشط المُدارة هي إعدادات برمجية نقية لمصادر Kotlin المضمّنة بالتطبيق. لا تتضمن تثبيت ملفات APK أو تحميل أكواد خارجية." else "Managed Extensions are pure configuration for bundled Kotlin scrapers. No APK installation or dynamic class loading."
    fun addManagedExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة مصدر جديد" else "Add Managed Scraper"
    fun editManagedExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعديل المصدر" else "Edit Managed Scraper"
    fun deleteManagedExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف المصدر نهائياً" else "Delete Managed Scraper"
    fun deprecateManagedExtension(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إحالة إلى التقاعد (Deprecate)" else "Deprecate Extension"
    fun scraperKeyLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مفتاح الكاشط (Scraper Key)" else "Scraper Key (e.g. qfilm)"
    fun baseUrlLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الرابط الأساسي (HTTPS)" else "Base URL (HTTPS)"
    fun searchUrlLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رابط البحث (Search URL)" else "Search URL Pattern (Optional)"
    fun runtimeApiVersionLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إصدار الـ Runtime API" else "Runtime API Version"
    fun definitionVersionLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إصدار التعريف (Definition Version)" else "Definition Version"
    fun priorityLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الأولوية (Priority)" else "Priority (Higher = First)"
    fun statusActive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط (ACTIVE)" else "ACTIVE"
    fun statusMaintenance(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صيانة (MAINTENANCE)" else "MAINTENANCE"
    fun statusDisabled(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معطل (DISABLED)" else "DISABLED"
    fun statusDeprecated(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "متقاعد (DEPRECATED)" else "DEPRECATED"
    fun confirmDeprecateTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد إحالة المصدر للتقاعد" else "Confirm Deprecation"
    fun confirmDeprecateMsg(name: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سيتم وسم مصدر '$name' كمتقاعد ولن يتم تنشيطه تلقائياً." else "Extension '$name' will be marked as DEPRECATED and will no longer be used for playback."
    fun legacyExtensionsNotice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافات APK القديمة" else "Legacy APK Extensions"

    // Phase EXT-CANONICAL-01: Content-Type Specific Search Ordering
    fun searchOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "ترتيب البحث" else "Search Order"
    fun searchOrderSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أولوية البحث للمشغّل بحسب نوع المحتوى" else "Content-type search priority policy"
    fun searchOrderBanner(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديد أولويات البحث للمشغّل في الأفلام والمسلسلات والأنمي بشكل مستقل. الترتيب من الأعلى للأسفل يحدد تسلسل فحص السيرفرات." else "Configure independent search priority policies for Movies, TV Series, and Anime. The top-to-bottom sequence dictates execution order in the Users App."
    fun movieSearchOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أولوية الأفلام (Movies)" else "Movie Search Order"
    fun tvSearchOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أولوية المسلسلات (TV Series)" else "TV Series Search Order"
    fun animeSearchOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أولوية الأنمي (Anime)" else "Anime Search Order"
    fun moveUp(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحريك لأعلى" else "Move Up"
    fun moveDown(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحريك لأسفل" else "Move Down"
    fun addExtensionToOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافة كاشط للترتيب" else "Add Scraper"
    fun removeFromOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إزالة من الترتيب" else "Remove"
    fun saveSearchOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حفظ ترتيب البحث" else "Save Search Order"
    fun resetOrderDefaults(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "استعادة الترتيب التلقائي" else "Reset to Defaults"
    fun discardChanges(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تراجع عن التعديلات" else "Discard Changes"
    fun unsavedChangesWarning(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "توجد تعديلات غير محفوظة" else "Unsaved changes pending"
    fun noExtensionsInOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد كواشط مضافة في هذا القسم" else "No scrapers configured in this category"
    fun disabledAtRuntimeNotice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معطل حالياً (سيتخطاه المشغّل تلقائياً)" else "DISABLED (Skipped by runtime player)"
    fun selectScraperToAdd(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اختر الكاشط المؤهل للإضافة:" else "Select an eligible scraper to append:"
    fun allEligibleScrapersAdded(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تمت إضافة جميع الكواشط المؤهلة لهذا القسم" else "All eligible scrapers are already in this category"
    fun tabExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الكواشط والإضافات" else "Scrapers Catalog"
    fun tabSearchOrder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "ترتيب وأولويات البحث" else "Search Order"

    // Phase C3: Support Conversations & Admin Desk
    fun supportInbox(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "صندوق الدعم الفني" else "Support Desk"
    fun supportInboxSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "محادثات المستخدمين واستفسارات الدعم" else "User support threads & inquiries"
    fun supportChat(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "محادثة الدعم" else "Support Chat"
    fun supportChatSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الرد الفوري ومتابعة المشكلة" else "Live response & issue resolution"
    fun supportStatusOpen(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مفتوحة" else "OPEN"
    fun supportStatusPending(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيد الانتظار" else "PENDING"
    fun supportStatusResolved(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم الحل" else "RESOLVED"
    fun supportStatusClosed(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مغلقة" else "CLOSED"
    fun typeReplyHint(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اكتب رداً رسمياً للمستخدم..." else "Type an official support reply..."
    fun sendReplyButton(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إرسال الرد" else "Send Reply"
    fun noSupportConversations(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد محادثات دعم حالياً" else "No support conversations found"
    fun noMessagesYet(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد رسائل في هذه المحادثة بعد" else "No messages in this thread yet"
    fun unreadBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير مقروء" else "UNREAD"
    fun supportAdminBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فريق الدعم" else "ADMIN SUPPORT"
    fun supportUserBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المستخدم" else "USER"
    fun changeStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تغيير حالة المحادثة" else "Change Status"
    fun deleteConversationConfirm(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد حذف المحادثة" else "Confirm Delete Thread"
    fun deleteConversationPrompt(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "هل أنت متأكد من حذف محادثة الدعم هذه نهائياً؟ لا يمكن التراجع عن هذا الإجراء." else "Are you sure you want to permanently delete this support conversation? This action cannot be undone."

    // Phase C4: Pro Requests Administration
    fun proRequests(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "طلبات الترقية (Pro)" else "Pro Requests"
    fun proRequestsSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مراجعة واعتماد طلبات الاشتراك المدفوع" else "Review & verify subscription upgrade requests"
    fun proRequestStatusPending(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيد المراجعة" else "PENDING"
    fun proRequestStatusApproved(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معتمد" else "APPROVED"
    fun proRequestStatusRejected(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مرفوض" else "REJECTED"
    fun approve(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اعتماد الطلب" else "Approve"
    fun reject(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رفض الطلب" else "Reject"
    fun rejectionReasonLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سبب الرفض" else "Rejection Reason"
    fun rejectionReasonPrompt(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "يرجى كتابة سبب رفض الطلب للمستخدم..." else "Enter reason for rejecting this request..."
    fun adminNoteLabel(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "ملاحظة المشرف (اختياري)" else "Admin Note (Optional)"
    fun confirmApprovalTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد اعتماد طلب الترقية" else "Confirm Request Approval"
    fun confirmApprovalMsg(email: String, plan: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "هل أنت متأكد من اعتماد طلب المستخدم '$email' لخطة '$plan'؟" else "Are you sure you want to approve the request for '$email' (Plan: $plan)?"
    fun requestDetails(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفاصيل طلب الترقية" else "Request Details"
    fun noProRequests(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد طلبات ترقية مطابقة" else "No Pro upgrade requests found"
    fun requestedPlan(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الخطة المطلوبة" else "Requested Plan"
    fun requestedDuration(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المدة المطلوبة" else "Requested Duration"
    fun paymentMethod(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "طريقة الدفع" else "Payment Method"
    fun paymentProof(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إثبات الدفع" else "Payment Proof"
    fun userNote(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "ملاحظة المستخدم" else "User Note"

    // Pro Metrics & Labels
    fun metricTotal(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الإجمالي" else "Total"
    fun metricPending(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيد الانتظار" else "Pending"
    fun metricApproved(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معتمد" else "Approved"
    fun metricRejected(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مرفوض" else "Rejected"
    fun proSearchPlaceholder(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بحث بالمستخدم، البريد، الخطة، أو المعرّف..." else "Search by user, plan, or request ID..."
    fun proFilterAll(count: Int, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الكل ($count)" else "ALL ($count)"
    fun sectionUserInfo(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معلومات المستخدم" else "USER INFORMATION"
    fun sectionRequestInfo(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بيانات الطلب والاشتراك" else "REQUEST INFORMATION"
    fun sectionReviewInfo(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بيانات المراجعة والاعتماد" else "STATUS & REVIEW"
    fun labelUser(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المستخدم" else "User"
    fun labelEmail(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "البريد الإلكتروني" else "Email"
    fun labelUid(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معرّف الحساب (UID)" else "Account UID"
    fun labelReviewedBy(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تمت المراجعة بواسطة" else "Reviewed By"
    fun labelReviewedAt(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تاريخ المراجعة" else "Reviewed At"
    fun labelStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الحالة" else "Status"
    fun statusApprovedText(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "✓ تم الاعتماد" else "✓ Approved"
    fun statusRejectedText(reason: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "✕ مرفوض: $reason" else "✕ Rejected: $reason"
    fun statusPendingText(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيد الانتظار" else "Pending Review"
    fun approvalSuccessMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم اعتماد طلب الترقية بنجاح" else "Request approved successfully"
    fun rejectionSuccessMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم رفض الطلب بنجاح" else "Request rejected successfully"
    fun deleteSuccessMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم حذف الطلب بنجاح" else "Request deleted successfully"
    fun rejectionReasonRequiredMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سبب الرفض إلزامي ولا يمكن تركه فارغاً" else "Rejection reason cannot be blank"
    fun confirmDeleteProRequestTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تأكيد حذف طلب الترقية" else "Confirm Delete Request"
    fun confirmDeleteProRequestMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "هل أنت متأكد من رغبتك في حذف طلب الترقية هذا نهائياً؟" else "Are you sure you want to permanently delete this upgrade request?"

    // Phase C5: User Management & Account Administration
    fun metricBanned(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المحظورين" else "Banned"
    fun metricPremium(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المشتركين" else "Premium"
    fun sectionAccount(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "بيانات الحساب" else "ACCOUNT"
    fun sectionSubscription(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الاشتراك والترقية" else "SUBSCRIPTION"
    fun sectionAccountRestrictions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "القيود والحظر" else "ACCOUNT RESTRICTIONS"
    fun sectionActivityMetadata(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "النشاط والبيانات الوصفية" else "ACTIVITY / METADATA"
    fun sectionAdminActions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إجراءات المشرف" else "ADMIN ACTIONS"
    fun labelDisplayName(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الاسم الظاهر" else "Display Name"
    fun labelAccountStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حالة الحساب" else "Account State"
    fun accountStatusActive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط" else "Active"
    fun accountStatusInactive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط" else "Inactive"
    fun accountStatusGoodStanding(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "وضع سليم" else "GOOD STANDING"
    fun labelAppVersion(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إصدار تطبيق العميل" else "Client App Version"
    fun labelDeviceLimit(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حد الأجهزة النشطة" else "Device Limit"
    fun labelLastActive(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "آخر نشاط" else "Last Active"
    fun labelLastLogin(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "آخر تسجيل دخول" else "Last Login"
    fun labelSubscriptionTier(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "فئة الاشتراك" else "Subscription Tier"
    fun labelSubscriptionStatus(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حالة الاشتراك" else "Subscription Status"
    fun labelSubscriptionExpiration(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تاريخ انتهاء الاشتراك" else "Subscription Expiration"
    fun labelBanState(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حالة الحظر" else "Ban State"
    fun labelBanExpiration(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تاريخ انتهاء الحظر" else "Ban Expiration"

    // Phase C6: Admin Analytics & Operational Dashboard
    fun tabOverview(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نظرة عامة" else "Overview"
    fun tabUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إدارة المستخدمين" else "Users"
    fun dashboardOverviewTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لوحة المؤشرات التشغيلية" else "Operational Dashboard"
    fun dashboardOverviewSubtitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "متابعة حية لمؤشرات النظام والأنشطة الإدارية" else "Live operational metrics & system analytics"
    fun kpiUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المستخدمين والحسابات" else "Users & Accounts"
    fun kpiSubscriptions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الاشتراكات والخطط" else "Subscriptions & Plans"
    fun kpiSupport(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مكتب الدعم الفني" else "Support Desk"
    fun kpiProRequests(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "طلبات الترقية (PRO)" else "Pro Requests Queue"
    fun kpiExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "المكشطات والإضافات" else "Managed Extensions"
    fun kpiFeatureRestrictions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفصيل قيود الميزات" else "Feature Restrictions"
    fun kpiRecentActivity(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "أحدث الأنشطة الإدارية" else "Recent Administrative Activity"
    fun labelTotalUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إجمالي المستخدمين" else "Total Users"
    fun labelActiveUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "نشط (آخر 30 يوم)" else "Active (30d)"
    fun labelInactiveUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "غير نشط (>30 يوم)" else "Inactive (>30d)"
    fun labelGlobalBans(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر حساب كامل" else "Global Account Bans"
    fun labelFeatureRestrictedOnly(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيود ميزات فقط" else "Feature Restricted Only"
    fun labelTotalRestricted(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إجمالي المقيدين" else "Total Restricted"
    fun labelFreeUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مستخدم مجاني" else "Free Users"
    fun labelPremiumUsers(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مشتركي PRO / VIP" else "Premium Users"
    fun labelActivePremium(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك نشط" else "Active Premium"
    fun labelExpiredPremium(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "اشتراك منتهي" else "Expired Premium"
    fun labelTotalConversations(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إجمالي المحادثات" else "Total Conversations"
    fun labelOpenConversations(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "محادثات مفتوحة" else "Open / Pending"
    fun labelUnreadMessages(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "رسائل غير مقروءة" else "Unread Admin"
    fun labelPendingRequests(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيد المراجعة" else "Pending Review"
    fun labelApprovedRequests(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "طلبات معتمدة" else "Approved Requests"
    fun labelRejectedRequests(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "طلبات مرفوضة" else "Rejected Requests"
    fun labelTotalExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إجمالي الإضافات" else "Total Extensions"
    fun labelActiveExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إضافات نشطة" else "Active (Enabled)"
    fun labelMaintenanceExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيد الصيانة" else "In Maintenance"
    fun labelDisabledExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "معطلة" else "Disabled"
    fun labelDeprecatedExtensions(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "مهجورة" else "Deprecated"
    fun labelWatchRestricted(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر المشاهدة" else "Watch Restricted"
    fun labelDownloadRestricted(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر التحميل" else "Download Restricted"
    fun labelChatRestricted(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر الدردشة" else "Chat Restricted"
    fun labelStoryRestricted(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر القصص" else "Story Restricted"
    fun labelP2pRestricted(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حظر مشاركة P2P" else "P2P Restricted"
    fun quickAccess(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "الانتقال السريع" else "Quick Jump"
    fun viewAllLogs(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "سجل التدقيق الكامل" else "View All Audit Logs"
    fun emptyAuditLogs(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "لا توجد سجلات تدقيق حديثة" else "No recent audit activity found"
    fun refreshMetrics(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تحديث المؤشرات" else "Refresh Metrics"
    fun failedToLoadSection(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعذر تحميل بيانات هذا القسم" else "Failed to load section data"
    fun manage(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إدارة" else "Manage"
    fun retry(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "إعادة المحاولة" else "Retry"

    // Network Connectivity & Real-time Offline Sync Strings
    fun offlineBanner(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "وضع عدم الاتصال — يمكنك تعديل البيانات وسيتم المزامنة تلقائياً عند عودة الاتصال" 
        else "Offline Mode — You can continue working; changes will sync automatically once connected"
    fun weakConnectionBanner(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "الاتصال ضعيف — جارٍ إرسال الطلبات في الخلفية دون انقطاع..." 
        else "Weak Connection — Syncing operations in background..."
    fun connectionRestoredBanner(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "تم استقرار الاتصال ومزامنة جميع البيانات بنجاح" 
        else "Connected — All pending changes synced successfully"
    fun pendingSyncBadge(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "قيد المزامنة..." else "Syncing..."
    fun localSavedNotice(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "تم حفظ التعديل محلياً في قائمة الانتظار وسيتم إرساله فور استقرار الاتصال" 
        else "Change saved locally in queue; will sync automatically once online"
    fun pendingOperationsCount(count: Int, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "$count عمليات قيد المزامنة في الخلفية" 
        else "$count operation(s) pending sync in background"

    // Notifications & Maintenance Dialogs
    fun deleteNotificationConfirmTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "حذف الإشعار نهائياً؟" else "Delete Notification Permanently?"
    fun deleteNotificationConfirmMsg(title: String, lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "هل أنت متأكد من حذف الإشعار \"$title\" نهائياً من قاعدة البيانات؟ لا يمكن التراجع عن هذا الإجراء." 
        else "Are you sure you want to permanently delete notification \"$title\"? This action cannot be undone."
    fun longPressToDeleteTip(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "انقر مطولاً على أي إشعار لحذفه نهائياً" else "Long press any notification to delete permanently"
    fun enableMaintenanceConfirmTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تفعيل وضع الصيانة العام؟" else "Enable Maintenance Mode?"
    fun disableMaintenanceConfirmTitle(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تعطيل وضع الصيانة العام؟" else "Disable Maintenance Mode?"
    fun enableMaintenanceConfirmMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "تفعيل وضع الصيانة سيؤدي إلى حظر جميع مستخدمي تطبيق CineStream من تشغيل الوسائط والوصول إلى المحتوى فوراً. هل أنت متأكد من المتابعة؟" 
        else "Enabling maintenance mode will immediately block CineStream users from playing media and accessing content. Are you sure?"
    fun disableMaintenanceConfirmMsg(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) 
        "تعطيل وضع الصيانة سيعيد إمكانية وصول كافة المستخدمين وتشغيل التطبيق بشكل طبيعي فوراً. هل أنت متأكد؟" 
        else "Disabling maintenance mode will restore normal access to all CineStream users immediately. Proceed?"
    fun dataRefreshed(lang: AppLanguage) = if (lang == AppLanguage.ARABIC) "تم تحديث البيانات بنجاح" else "Data refreshed successfully"
}
